### ISSUE TITLE
Wood spawn indicator

### ISSUE THREAD

**Issue by hoichael** [Noah2610/LD46#24]
We've talked about maybe having some kind of indicator for wood spawning that's visible to the player under all circumstances (including wood spawning in darkness). Maybe something like a short animation that plays (once) at the spawn location?
The more i think about it in terms of designing a coherent gameplay loop, the more sense a system like this makes, for multiple reasons. Would be great to have, though not essential by any means. Medium priority I guess.

**Comment by Noah2610** [comment]
Let's see how it feels without the wood ever being visible.
I think it could also be cool, if the player has to wander out into the unknown, without any goal or direction.

**Comment by Noah2610** [comment]
On wood spawn, spawn entity with animation, delete when animation done.
