### ISSUE TITLE
Have player inventory dynamically affect movement values 

### ISSUE THREAD

**Issue by hoichael** [Noah2610/LD46#29]
1 wood = slower movement and less jump height
2 woods = slower movement and less jump height
3+ woods = slower movement and no jump at all / 0 jump height

**Comment by Noah2610** [comment]
Multiply player speed and jump strength depending on how much wood they have?
Something like this:
```
factor = 10.0
speed = 100.0

// With 0 wood
//                         vvv this is the wood amount
new_speed = speed * (1.0 + 0.0 / -factor)
new_speed == 100.0

// With 1 wood
//                         vvv this is the wood amount
new_speed = speed * (1.0 + 1.0 / -factor)
new_speed == 90.0

// With 2 wood
//                         vvv this is the wood amount
new_speed = speed * (1.0 + 2.0 / -factor)
new_speed == 80.0
```

**Comment by Noah2610** [comment]
This formula and factor decrease these values:
- `acceleration`
- `max_velocity`
- `jump_strength`
- `climb_acceleration`
- `max_climb_velocity`
